### ISSUE TITLE
-G flag should set the environment variables GROUP and JOBSUB_GROUP

### ISSUE THREAD

**Issue by shreyb** [marcmengel/jobsub_lite#1]
Currently, the -G flag to jobsub_lite commands sets the group of the submission, which is only used in tarfile upload.  We need to also populate the GROUP environment variable with this value for submission to the DUNE global pool, since otherwise, token generation (and thus authorization to submit) fails.

The current set of steps needed to submit a job to GPGrid is:

```source /grid/fermiapp/products/common/etc/setups
export GROUP=dune
jobsub_submit -G dune  --resource-provides=usage_model=OPPORTUNISTIC,DEDICATED  file:///home/sbhat/TestJobs/basicsleep.sh 123
```
For the DUNE pool, the process is:

```source /grid/fermiapp/products/common/etc/setups
export _condor_COLLECTOR_HOST=dunegpcoll02.fnal.gov
export GROUP=dune
jobsub_submit -G dune  --resource-provides=usage_model=OPPORTUNISTIC,DEDICATED  file:///home/sbhat/TestJobs/basicsleep.sh 123
```
The third line is unnecessary, since we're already specifying group.

**Comment by marcmengel** [comment]
So I believe the pull request resolves this.  Closing it out
