### ISSUE TITLE
Remove any hard-coded hostnames from code, put into separate config that is version-controlled on private  git

### ISSUE THREAD

**Issue by shreyb** [marcmengel/jobsub_lite#106]
At yesterday's jobsub project meeting, we discussed how much information is reasonable to have on a public repository.  We decided that as much as possible, we should try to remove hostnames from this repository, even if there's no actual security threat.  

The current idea is to keep the configuration in a separate RPM, version-controlled on a private git repository.  Then, when jobsub_lite is deployed, both the jobsub_lite RPM and the config rpm should be installed.

**Comment by shreyb** [comment]
Assigned to @marcmengel  since he's started work on it. Marc - feel free to unassign the issue if you need to step away from it.

**Comment by marcmengel** [comment]
So I have a pull request for phase 1 of this; which concentrates hostnames into config.d and spec subirectories.

I have made a new repo https://github.com/marcmengel/jobsub_lite_config with just those config.d and spec subdirectories.

Next is to actually remove the config.d and spec subdirectories from the main repo... the question is do we just remove them at the HEAD or do we do git filter-branch evil to clean them out throughout history and clean out the past references...

**Comment by shreyb** [comment]
This is completed now, right?

**Comment by shreyb** [comment]
This is completed, right?  After talking with FNAL cybersecurity, they said we didn't have to git-filter-branch anything.

**Comment by marcmengel** [comment]
Yes, I believe we're done.
