### ISSUE TITLE
Document list of Environment Variables we clear in #84

### ISSUE THREAD

**Issue by shreyb** [marcmengel/jobsub_lite#119]
In #84, we implemented the automatic (but opt-out-able) clearing of certain environment variables.  These need to be documented in the FIFE Mediawiki at fifewiki.fnal.gov.

**Comment by marcmengel** [comment]
It is at: https://fifewiki.fnal.gov/wiki/Jobsub_Wrapper_Scripts#Startup_actions

Although, I think we did **not** make it opt-out-able...

**Comment by shreyb** [comment]
Do you want to do that as a part of this issue, or should I split it out?

**Comment by marcmengel** [comment]
So the opt-out flag is added, as are the docs.
