### ISSUE TITLE
Create man page(s)

### ISSUE THREAD

**Issue by retzkek** [marcmengel/jobsub_lite#127]
We really should have man pages, it's just plain rude not to for CLI tools, even in 2022 :) 

@DrDaveD is really great about writing good man pages, htgettoken is a good model to follow. https://github.com/fermitools/htgettoken/blob/master/htgettoken.1

**Comment by marcmengel** [comment]
Added skeleton manpages to start, #128.

**Comment by shreyb** [comment]
Is there any work left on this issue?  It looks pretty done to me.
