### ISSUE TITLE
Option `--tar_file_name dropbox:///path` doesn't seem to work properlky

### ISSUE THREAD

**Issue by vitodb** [marcmengel/jobsub_lite#134]
In the submission I use
```
--tar_file_name dropbox:///home/vito/sbndcode_v09_59_00_e20_prof.tar --use-cvmfs-dropbox
```
the tarball is uploaded to RCDS, but jobs try to get it as local tarball.
In the stderr I get
```
...
 checking prefix / -> /
Exception:Path dropbox:///home/vito/sbndcode_v09_59_00_e20_prof.tar did not match in configuration
at:Tue Sep 27 21:57:41 2022

tar (child): .unwind_1/sbndcode_v09_59_00_e20_prof.tar: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
...
```
and the simple.sh script has
```
# -f files for input


# --tar_file_name for input

  
    # RCDS unpacked tarfile
    
      INPUT_TAR_FILE=/cvmfs/fifeuser2.opensciencegrid.org/sw/sbnd/18bd649a28f4ea976629004c83334d341442d36ca802c7f93fe6a14154b24d30
      export INPUT_TAR_FILE
    
  

      # tarfile to transfer and unpack
    mkdir .unwind_1
    
    ${JSB_TMP}/ifdh.sh cp dropbox:///home/vito/sbndcode_v09_59_00_e20_prof.tar .unwind_1/sbndcode_v09_59_00_e20_prof.tar
    tar --directory .unwind_1 -xzvf .unwind_1/sbndcode_v09_59_00_e20_prof.tar
    
      INPUT_TAR_FILE_1=`pwd`/.unwind_1
      export INPUT_TAR_FILE_1
```

**Comment by marcmengel** [comment]
Hm... that's weird.  The "dropbox:" string shouldn't be getting through to the simple.sh script at all, it should have been converted to a /cvmfs path...  
ah..., there we go.  It was putting the converted path *and* the dropbox: path in.. .sigh. 
```
         if tfn.startswith("dropbox:"):
            # move it to dropbox area, pretend they gave us plain path
            path = tarfile_in_dropbox(args, tfn[8:])
            if path:
                res.append(path)
            else:
                res.append(tfn.replace("dropbox:", ""))

        res.append(tfn)
```
in the `if path:` bit it should be setting tfn to the value, not appending the value, so the append following will put it in the result.

**Comment by marcmengel** [comment]
Ack! forgot to start a branch; pushed this on master.

**Comment by marcmengel** [comment]
Okay, fixed master. made a drobpox_fix branch..

**Comment by vitodb** [comment]
There is still a back compatibility issue for this option against `jobsub_client`.
In `jobsub_client` the env var `INPUT_TAR_FILE` was set as `${CONDOR_DIR_INPUT}/mytar` (this was a synlink),
but in `jobsub_lite` the env var `INPUT_TAR_FILE` is set directly to the RCDS path.
In `fife_utils/fife_wrap` to setup the user code from the tarball we look for the code in folders proovided this way
```
d = os.environ.get("INPUT_TAR_DIR_LOCAL",os.path.dirname(os.environ.get("INPUT_TAR_FILE", "/tmp/x")))
```
specifically `os.path.dirname(os.environ.get("INPUT_TAR_FILE", "/tmp/x"))` strips on dir level and we can't reach the user code.

**Comment by marcmengel** [comment]
I'm now setting INPUT_TAR_DIR_LOCAL for the rcds directory, which does not get the last component truncated.
I also included a loop to wait for it to appear, like the one in the old jobsub.

**Comment by vitodb** [comment]
I submitted some test jobs and now tarballs are handled properly.
Thanks to get this fixed!
