### ISSUE TITLE
Document jobsub_hold and jobsub_release

### ISSUE THREAD

**Issue by shreyb** [marcmengel/jobsub_lite#141]
On this page:

https://github.com/marcmengel/jobsub_lite/wiki#jobsub_transfer_data

We should then provide a link from the FIFE wiki here-ish:
https://fifewiki.fnal.gov/wiki/Jobsub_Lite

**Comment by marcmengel** [comment]
Added option summaries for the other jobsub commands, and a link to the Fife Wiki.

**Comment by shreyb** [comment]
Updated documentation with new flags.  Closing issue.
