### ISSUE TITLE
Method/service for fetching job logs over the web

### ISSUE THREAD

**Issue by retzkek** [marcmengel/jobsub_lite#147]
Currently jobsub server makes job logs available to authenticated users over https, serving them from the local sandbox (which is where it submits jobs from and condor puts output into) on the schedd, with a cron job to clean those up after 30 days. This service is used by landscape jobview to provide a central SSO-authenticated method to access these logs.

Now, with jobsub_lite, the "sandbox" is on the user's submit machine, with input and output only available in the spool dir on the schedd, retrievable with `jobsub_fetchlog` (which uses `condor_transfer_data`), until the job is removed from the queue (either manually or by configuration). We have a couple options to provide web access for jobsub_lite jobs:

## Option 1: run server on schedd

Run a web service on each schedd that can serve files from the condor spool dirs, which would require tweaking some permissions knobs in condor.

### Pros
* Relatively straightforward to setup
* similar to old setup, simple integration with landscape jobview

### Cons
* condor includes stuff like credentials in the spool dir
* spool dir only exists while job is in queue, so we either keep jobs in the queue for 30 days (which has side-effects, like jobs not showing up in history until then) or reduce the availability window
* one more thing to maintain

## Option 2: dCache

Have condor put the output into a shared location, like dcache (or ceph via s3, coming soon(ish)). See https://htcondor.readthedocs.io/en/latest/users-manual/file-transfer.html?#file-transfer-using-a-url

### Pros
* Leverages existing services
* Files available after job leaves queue, cleaned up by dCache
* less things to maintain

### Cons 
* May require a custom file transfer plugin (or maybe http wil "just work"?)
* Need to verify dCache areas all set up for everyone in every group

### Steps

- [X] create area in scratch dCache for logs - RITM1589453 
- [x] add scope to tokens to write to the dCache area - RITM1602974
- [x] #255
- [x] job data for jobsub_lite jobs in Lens (currently expects to find "completed" jobs in history, not true now)
- [x] jobview fetch output from dCache

**Comment by shreyb** [comment]
I think you've covered all the reasonable options, and in good detail.  Which one are you leaning towards?

**Comment by retzkek** [comment]
I very much prefer Option 2, it's keeping with the "stick to condor" ethos of this project, and will reduce future maintenance and operation burden over Option 1 (as much as I would enjoy developing a new service). Unfortunately it doesn't "just work" in testing so far, our Vault tokens are formatted differently than the file transfer plugin expects. Should be a simple fix, we'll see what condor devs say.

I'm really intrigued by the s3 support, but I don't think our ceph project will be in a production state for some time yet. If we treated it as an implementation detail we could switch from dcache to ceph in the future maybe. 

Further consideration then is where exactly to put the logs:
1. Under `/<experiment>/scratch/users/<user>`, which currently is included with `storage.create` scope for all (?) tokens. (ed: actually at least one vo has `/<experiment>/users/<user>` instead). Advantage is these areas exist already, and users could directly access their (or others) logs using existing dcache access policies.
2. Some new location in scratch dcache, which we could add to all token scopes (or maybe pass a different credential?). Advantage of this is that we'd have full control over the area, and could change implementation details transparently in the future.

**Comment by retzkek** [comment]
All tasks completed - jobsub (master branch) wrappers copy logs to dcache, lens is shiny and new and gets correct information for all jobs, and jobview goes to dcache for logs for all jobsub_lite jobs (where `JobsubVersion` classad attribute begins with `lite`).

 Everything is running on landscapeitb for testing. I'll close this once everything is running in production.

**Comment by marcmengel** [comment]
Yay!
