### ISSUE TITLE
Document production jobs on fifewiki

### ISSUE THREAD

**Issue by shreyb** [marcmengel/jobsub_lite#149]
Document here:

https://fifewiki.fnal.gov/wiki/Getting_started_with_jobsub_lite

Give an idea of managed tokens, with tentative link to managed tokens on FIFE wiki.

**Comment by marcmengel** [comment]
I put a draft up on the wiki page.  It could probably use a review and some touch-up.

**Comment by shreyb** [comment]
Cool - thanks Marc!

**Comment by shreyb** [comment]
Made a couple of revisions.  Does this look good to you, Marc?

**Comment by marcmengel** [comment]
Yes, thanks!

**Comment by shreyb** [comment]
Made one final edit.  I'm good with calling this done.
