### ISSUE TITLE
Clean up FIFE wiki jobsub_lite page (FNAL-facing only)

### ISSUE THREAD

**Issue by shreyb** [marcmengel/jobsub_lite#152]
Clean up this page:

https://fifewiki.fnal.gov/wiki/Jobsub_Lite

**Comment by marcmengel** [comment]
Made a first stab at this...

**Comment by shreyb** [comment]
@marcmengel How does it look now?  I just organized the page into sections.

https://fifewiki.fnal.gov/wiki/Jobsub_Lite

**Comment by marcmengel** [comment]
Looks good! @shreyb
