### ISSUE TITLE
jobsub_lite option `--dag` creates malformed DAG

### ISSUE THREAD

**Issue by vitodb** [marcmengel/jobsub_lite#163]
Using an XML DAG like the following one:
```
<serial>
jobsub -e SLEEP1 -n -G sbnd --expected-lifetime=5m --memory=500MB --disk=1GB --onsite-only -N 1 -l +CI_VALIDATION_STAGE="test_vito_01" file:///usr/bin/sleep ${SLEEP1}
jobsub -e SLEEP2 -n -G sbnd --expected-lifetime=5m --memory=500MB --disk=1GB --onsite-only -N 1 -l +CI_VALIDATION_STAGE="test_vito_02" file:///usr/bin/sleep ${SLEEP2}
jobsub -e SLEEP3 -n -G sbnd --expected-lifetime=5m --memory=500MB --disk=1GB --onsite-only -N 1 -l +CI_VALIDATION_STAGE="test_vito_03" file:///usr/bin/sleep ${SLEEP3}
</serial>
```
creates a DAG with few issues.

1. the `dag.dag` file has lines with `#` that condor doesn't like. Also the line ` PARENT` is appended to the previous line, this makes an invalid DAG. Adding some extra empty line could help to give the DAG better readability.
2. the `stage_N.cmd` files have incorrect lines, the diff output with the correct cmd file has
``` 
23,24c23,24
< transfer_input_files = sleep,simple.cmd
< transfer_output_files = simple.cmd,simple.sh,sleep
---
> transfer_input_files = sleep,stage_1.cmd
> transfer_output_files = stage_1.cmd,stage_1.sh,sleep
```
i.e. it has `simple` instead of `stage_N`

3. similarly `stage_N.sh` files have  `simple` instead of `stage_N`

**Comment by marcmengel** [comment]
Fixed in #165.
