### ISSUE TITLE
jobsub_q should be able to filter by Owner of job

### ISSUE THREAD

**Issue by shreyb** [marcmengel/jobsub_lite#182]
In jobsub_client, we have an option "--user" that can filter the results of jobsub_q  by user.  We should have that in jobsub_lite.

**Comment by marcmengel** [comment]
condor_q and current jobsub_q take just the username, so we could add a no-op --user flag...

**Comment by shreyb** [comment]
Ooh - that would be nice.  Though we should be careful, because you can ALSO say `condor_q <jobid>`.  I think a no-op flag would still be OK.  If we wanted to be super-safe, we could of course have the --user flag create a constraint for the Owner.
