### ISSUE TITLE
f.close should be f.close()

### ISSUE THREAD

**Issue by shreyb** [marcmengel/jobsub_lite#20]
Currently, on this line:
https://github.com/marcmengel/jobsub_lite/blob/c26e3631f7412a6876bc9bc6b99539d51b1428ad/lib/creds.py#L29

there's a call to f.close.  This should be f.close()

**Comment by goodenou** [comment]
I have changed this in my modifications for Issue 12.

**Comment by shreyb** [comment]
@goodenou This is now fixed - please note that you'll need to rebase before opening a PR for #12.
