### ISSUE TITLE
Feature request: provide feature for bash script to get jobid back from jobsub_submit

### ISSUE THREAD

**Issue by shreyb** [marcmengel/jobsub_lite#237]
From @hschellman:

Is there a way for a bash script to get the jobid back for storage - or have it emailed to me on submit or something? my minerva script does a
submit | grep jobsub which I guess does it. 

@shreyb note:  We'll have to probably discuss with Heidi the parameters around such a feature.

**Comment by marcmengel** [comment]
So a shell function like:
```
slurp_jobid() {
    while read line
    do
        echo "$line"
        case "x$line" in 
        xUse?job?id*retrieve?output)
           set : $line
           jobid=$5
           echo $jobid >> $HOME/.submitted_jobs
           ;;
        esac
    done
}
```
will record the jobids in $HOME/.submitted_jobs, if you: 

`jobsub_submit ... | slurp_jobid`

one could easily modify it to send email, etc.   [This is the approach poms_jobsub_wrapper uses]

**Comment by marcmengel** [comment]
But I suppose it might be more user-friendly to have a jobsub option that does it... something like
jobsub_submit --report_jobid 'Mail -s "job ${jobid} launched" user@fnal.gov'  
or
jobsub_submit --report_jobid 'echo ${jobid} >> $HOME/.launched_jobs'

**Comment by marcmengel** [comment]
If we do the latter it would be :
* a new option in get_parser
* a for loop (for multiple such options) and os.system call in lib/condor.py in submit() where we echo the jobid now. 
so about 10 lines of code?

**Comment by shreyb** [comment]
@hschellman:  Are you thinking something like the options @marcmengel laid out above?

**Comment by marcmengel** [comment]
We should merge this or tie it to #281...

**Comment by shreyb** [comment]
@hschellman:  I just wanted to alert you that this feature will be going into 1.2.1.
