### ISSUE TITLE
update tests for test_tarfiles.py / do_tarballs, test_submit_wait_int

### ISSUE THREAD

**Issue by marcmengel** [marcmengel/jobsub_lite#243]
for:
*  all permutations of --use-pnfs/cvmfs-dropbox and dropbox: , full/relative paths on -f 
*  all permutations of --use-pnfs/cvmfs-dropbox and dropbox: full/relative paths on --tar-file-name 
*  make sure no dropbox: ends up in the filtered arguments.
* above permutations in actual submissions, and check for uploaded file(s) in documented locations.

**Comment by shreyb** [comment]
This was addressed in #252, right?

**Comment by marcmengel** [comment]
I should still go back and do relative and absolute paths...

**Comment by marcmengel** [comment]
On second thought, I'm going to call this done with #252.
