### ISSUE TITLE
jobsub_transfer_data does not respect the JOBSUB_GROUP envrionment variable

### ISSUE THREAD

**Issue by kherner** [marcmengel/jobsub_lite#27]
If I set JOBSUB_GROUP to say dune and then try jobsub_transfer_data myjobid, I get a failure:

$ jobsub_transfer_data 107@dunegpschedd02.fnal.gov
sh: line 1: _Production_50762: command not found
Checking if /tmp/x509up_u50762 can be reused ... yes
...........++++++
.....++++++
sh: line 1: _Production_50762: command not found
sh: line 2: /Role=Production: No such file or directory
sh: line 1: _Production_50762: command not found
htgettoken: Kerberos negotiate with https://fermicloud543.fnal.gov:8200/v1/auth/kerberos-dunepro_default/login failed: HTTPError: HTTP Error 400: Bad Request: missing client token
sh: line 1: -r: command not found

But all works happily with` jobsub_transfer_data -G dune 107@dunegpschedd02.fnal.gov`.

**Comment by marcmengel** [comment]
I believe it only looks for GROUP currently, not JOBSUB_GROUP...

**Comment by goodenou** [comment]
We have decided to simplify things and only accept the environment variable 'GROUP' in the jobsub_lite code. References to 'JOBSUB_GROUP' and 'EXPERIMENT' have been removed from the code in PR 93.
