### ISSUE TITLE
Investigate DAG job output upon successful submission

### ISSUE THREAD

**Issue by shreyb** [marcmengel/jobsub_lite#282]
Copied from ServiceNow ticket RITM1621604

This is based on a request from Tejin Cai. He says that the structure of the output in jobsub_lite is such that the successful submission info is buried among a bunch of other printout. He gives these examples.

Below is the printout from jobsub_client with a successful submission:

FILETIMESTAMP%3D%24%28date%20-u%20%2B%25Y%25m%25dT%25H%25M%25SZ%29
--userscript True --ifdh_art --limit 1 --appvers v09_64_01d00 --schema
root --appname reco --appfamily art --addoutput '*_reReco.root' --dest
/pnfs/dune/scratch/dunepro/dropbox/mc/RITM1592444/reReco/NNBarAtm_hA_LFG
--declare_metadata --metadata_extractor json --addoutput1
'*_Pandora_Events.pndr' --dest1
/pnfs/dune/scratch/dunepro/dropbox/mc/RITM1592444/PandoraFiles/NNBarAtm_hA_LFG
--declare_metadata1 --metadata_extractor1 json --exe lar -- -c
reco_1dsignalprocessing_dune10kt_1x2x6_refactored.fcl -o
'%ifb___\\\_reReco.root' -n -1
WARNING:root:Notice: poms_client.get_task_id_for() is deprecated, use
get_submission_id
/fife/local/scratch/uploads/dune/dunepro/2023-01-17_013718.975098_2481

/fife/local/scratch/uploads/dune/dunepro/2023-01-17_013718.975098_2481/fife_wrap_20230117_013720_3419119_1.dag

submitting....

Submitting job(s).

1 job(s) submitted to cluster 43185877.

-----------------------------------------------------------------------

File for submitting this DAG to HTCondor :
/fife/local/scratch/uploads/dune/dunepro/2023-01-17_013718.975098_2481/fife_wrap_20230117_013720_3419119_1.dag.condor.sub

Log of DAGMan debugging messages :
/fife/local/scratch/uploads/dune/dunepro/2023-01-17_013718.975098_2481/fife_wrap_20230117_013720_3419119_1.dag.dagman.out

Log of HTCondor library output :
/fife/local/scratch/uploads/dune/dunepro/2023-01-17_013718.975098_2481/fife_wrap_20230117_013720_3419119_1.dag.lib.out

Log of HTCondor library error messages :
/fife/local/scratch/uploads/dune/dunepro/2023-01-17_013718.975098_2481/fife_wrap_20230117_013720_3419119_1.dag.lib.err

Log of the life of condor_dagman itself :
/fife/local/scratch/uploads/dune/dunepro/2023-01-17_013718.975098_2481/fife_wrap_20230117_013720_3419119_1.dag.dagman.log

-----------------------------------------------------------------------

These spacers ("----") really made it obvious where to look for in terms of
success or failure..

Below is the printout from jobsub_lite with a successful submission:

2_RITM1355274_reco_NNBarAtm_hA_BR_b5dcbd3b-0e9d-4048-b17a-70aec4decdba_slice_647743_stage_5
--exe lar -- -c reco_1dsignalprocessing_dune10kt_1x2x6_refactored.fcl
-o '%ifb___\\\_reReco.root' -n 5
WARNING:root:Notice: poms_client.get_task_id_for() is deprecated, use
get_submission_id
Submitting job(s).
1 job(s) submitted to cluster 57107980.
Use job id 57107980.0@jobsub01.fnal.gov to retrieve output
--2023-01-12 09:48:46--
https://pomsgpvm01.fnal.gov:8443/poms/update_submission?submission_id=1418912&jobsub_job_id=57107980@jobsub01.fnal.gov&status=New
Resolving pomsgpvm01.fnal.gov (pomsgpvm01.fnal.gov)... 131.225.67.18
Connecting to pomsgpvm01.fnal.gov
(pomsgpvm01.fnal.gov)|131.225.67.18|:8443... connected.
WARNING: cannot verify pomsgpvm01.fnal.gov's certificate, issued by
'/C=US/O=DigiCert Inc/CN=DigiCert TLS RSA SHA256 2020 CA1':
Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK
Ok.Length: 3 [text/html]
Saving to: 'STDOUT' 

@shreyb notes:  A lot of the "jobsub_lite" output seems to come from POMS.  Perhaps we could put the spacers in for DAGs, to make that clearer, but the rest of the issues seem to be out of scope.

**Comment by marcmengel** [comment]
We could just add some horizontal lines (equals signs/dashes) to the jobsub_submit output about the job id / and/or failure message to make it stand out?

**Comment by marcmengel** [comment]
Or looking at our outage announcements, we could have:

---------------------------------
...
Submitting job(s).

 DID IT WORK? 
 1 job(s) submitted to cluster 57107980.
Use job id [57107980.0@jobsub01.fnal.gov](mailto:57107980.0@jobsub01.fnal.gov) to retrieve output

-----
...
------------------------

**Comment by shreyb** [comment]
> We could just add some horizontal lines (equals signs/dashes) to the jobsub_submit output about the job id / and/or failure message to make it stand out?

I like that idea.
