### ISSUE TITLE
jobsub_version in templates should use the __version__ variable

### ISSUE THREAD

**Issue by retzkek** [marcmengel/jobsub_lite#306]
Instead it's forever pinned to 1.0.

https://github.com/marcmengel/jobsub_lite/blob/eeb7477b10cfb3072f86d1c3f634a5a4a251e879/lib/utils.py#L119

**Comment by retzkek** [comment]
And just a reminder (we probably need a comment too), that the version NEEDS to start with "lite" for jobview to work. It doesn't look at the version number, but I could see that being used in the future if we need to change something about how the logs are handled. So we probably want to lock down a format for that attribute. 

Oh and the title isn't quite right (or at least misleading), since we've got an underscore in `jobsub_version` while `__version__` has a dot. But there's no reason we couldn't stick a dot in `jobsub_version` that I can think of. Heck we could even put a space in it: `lite v1.0`.

**Comment by shreyb** [comment]
Noted.

**Comment by retzkek** [comment]
Just to record what @shreyb and I discussed, we think `{__title__}-{__version__}` is the way to go to get the constants out of the code. I'll change jobview to check if the version string contains "lite" instead of a prefix match, hopefully that's pretty future-proof.

**Comment by shreyb** [comment]
Code written, but I want to run a couple of quick tests before opening a PR.

**Comment by shreyb** [comment]
Ran the following tests:

1. `$ ~/jobsub_lite/bin/jobsub_submit --version`
jobsub_lite version 1.1.1
2. `$ ~/jobsub_lite/bin/jobsub_submit --support-email`
Email jobsub-support@fnal.gov for help.
3. `$ ~/jobsub_lite/bin/jobsub_q --version`
jobsub_lite version 1.1.1
4. `$ ~/jobsub_lite/bin/jobsub_q --support-email`
Email jobsub-support@fnal.gov for help.
5. `$ ~/jobsub_lite/bin/jobsub_fetchlog --version`
jobsub_lite version 1.1.1
6. `$ ~/jobsub_lite/bin/jobsub_fetchlog --support-email`
Email jobsub-support@fnal.gov for help.
7. jobsub_submit, but don't actually submit job.  Inspect .cmd file to make sure we get the right version:  
`~/jobsub_lite/bin/jobsub_submit -G fermilab -n file:///usr/bin/sleep 300`

In .cmd file:
```
+JobsubServerVersion="jobsub_lite-v1.1.1"
+JobsubClientVersion="jobsub_lite-v1.1.1"
```
PASS
