### ISSUE TITLE
-d flags exported as relative paths, rather than absolute paths

### ISSUE THREAD

**Issue by shreyb** [marcmengel/jobsub_lite#318]
In ServiceNow ticket RITM1652869, David Last (Minerva) reports an issue where the -d flags to jobsub_submit are exported as relative paths, and not absolute paths.  

His jobsub_submit command is something like this:

```
jobsub_submit --onsite --memory=4GB --disk=2GB --expected-lifetime=2h -N 1
-d OUT
/pnfs/scratch/path/he/has/access/to/write/in
-e IFDH_CP_MAX_RETRIES=1 --tar-file-name
dropbox:///path/to/tarball
file:///minerva/executable <args>
```

The expected behavior, then, is that we should create a directory, `out_OUT`, with the environment variable `$CONDOR_DIR_OUT` pointing to `out_OUT`.  The problem is, that in his script, he changes directories to `$CONDOR_SCRATCH_DIR`, runs his code, and then tries to copy it to `$CONDOR_DIR_OUT`, which is still `out_OUT` - a directory that doesn't exist in `$CONDOR_SCRATCH_DIR`.  He rightly points out that no matter where he changes directories to, `$CONDOR_DIR_OUT` should point to the output directory.

We need to change the code here (and in any other template in the same corresponding location, if applicable), to use absolute paths.
https://github.com/marcmengel/jobsub_lite/blob/master/templates/simple/simple.sh#L284

**Comment by marcmengel** [comment]
The fix is easy, just add a backtick pwd backtick slash; but also adding a test to make sure -D tag /outpath works while I'm at it...
