### ISSUE TITLE
Let DAG nodes inherit tarball path

### ISSUE THREAD

**Issue by vitodb** [marcmengel/jobsub_lite#320]
For DAG submissions in order to let each node to be aware of the RCDS path of a tarball it is needed to use the `--tar_file_name dropbox://` option for each DAG node.
I'm wondering if it could be possible to implement a feature that allows to use the `--tar_file_name dropbox://` option for the DAG submission and let all DAG nodes inherit the associated env var `INPUT_TAR_DIR_LOCAL` and other related stuff, so avoiding the need for each DAG node to (try to) upload the tarball to RCDS.

**Comment by marcmengel** [comment]
That was *supposed* to work already... I have reproduced this and fixed it; pull request forthcoming after tests...  The other thing I might still put in is if you have a --tar-file-name on the main command line and one in the dag lines, you should get *both* -- we should merge the lists, not override them
