### ISSUE TITLE
Implement a flag that skips RCDS publish check at submission

### ISSUE THREAD

**Issue by shreyb** [marcmengel/jobsub_lite#323]
Copied from ServiceNow ticket RITM1654874 by @hgreenlee:

This is a feature request to jobsub_lite developers.  I would like there to be a jobsub_submit option such that when jobsub_submit is invoked with option "-f dropbox://", jobsub_submit does not wait for RCDS upload before exiting and printing the submitted job id.  I don't care if waiting for RCDS stays as the default.  Obviously, this implies that the batch job wrapper has to be smart enough to wait for the RCDS upload (if it doesn't do that already).  The reasoning behind this request is that there are use cases where wall time of job submission is more valuable than wall time in batch jobs, even potentially at the expense of some batch job efficiency metric.

Extra notes by @shreyb:

I discussed this with @marcmengel, and we agreed that this was a useful and reasonable feature to add.  

However, since this does introduce risk that the job may fail due to the failure of RCDS to publish the tarball, this change MUST include a warning message of some sort to the user if they use this proposed flag that warns them of the risk, and instructs them to resubmit with the flag removed if they do not want to accept the risk.

**Comment by shreyb** [comment]
@retzkek idea: along with this, create a new classad that we store this information in, so we can monitor on which opt-in options were chosen from jobsub_lite.  So this would look something like:
```
+JobsubOptions="noWaitRCDS"
```

Or whatever the option name ends up being, but camel-cased.  

@retzkek : do you like `--no-wait-rcds`?  I was thinking `--skip-rcds-check` or maybe to even generalize it more, `--skip-upload-check`.  Thoughts?

**Comment by marcmengel** [comment]
What about` --skip-check=rcds` ?  Then we could add other skip-check types later without expanding the arglist significantly.  (not sure offhand what other checks folks might want us to skip, maybe tarfile permissions?)

**Comment by shreyb** [comment]
I like that idea a lot @marcmengel  - and then we'd have an in-code configuration of what the skip-checks options are, that we could dynamically load in the parser output?

**Comment by shreyb** [comment]
> +JobsubOptions="noWaitRCDS"

Forgot to add this in.  Need to do that.

The scripting portion is done, but we need to test it all.  Tests should be:

1. plain submit
2. submit -f file
3. submit -f file1 -f file 2
4. submit -f dropbox://file1 -f file 2
5. submit -f dropbox://file1 -f dropbox://file2
6. submit --tar-file-name dropbox://file1
7. submit --tar-file-name dropbox://file1 -f file2
8. submit --tar-file-name dropbox://file1 -f dropbox://file2
9.  submit --tar-file-name dropbox://file1 --tar-file-name dropbox://file2
10. submit --tar-file-name tardir://dir1 --tar-file-name dropbox://file2
11. 8.  submit --tar-file-name tardir://dir1 --tar-file-name tardir://dir2

I think that covers all cases.

**Comment by shreyb** [comment]
Added classad `JobsubSkipCheck` whose value is a comma-separated list in quotes.  An example would be:

`+JobsubSkipCheck="rcds"`

Or

`+JobsubSkipCheck="rcds,foo,bar"`

**Comment by shreyb** [comment]
Lots of little issues found in testing.  So far, tests 1-6 above pass.  Running (10) now.

**Comment by shreyb** [comment]
All tests without RCDS check pass.  Here are the details of the tests:

1.  plain submit: 66651774.0@jobsub02.fnal.gov - PASS

2.  submit -f file:  PASS
```~sbhat/jobsub_lite/bin/jobsub_submit -G nova --onsite -f /pnfs/nova/scratch/users/sbhat/a  file://dash-f.sh a
66652511.0@jobsub02.fnal.gov - BAD SCRIPT
66652541.0@jobsub02.fnal.gov - PASSED
```

3.  submit -f file1 -f file 2 - PASS
```
~sbhat/jobsub_lite/bin/jobsub_submit -G nova --onsite -f /pnfs/nova/scratch/users/sbhat/a -f /pnfs/nova/scratch/users/sbhat/b file://dash-f.sh a b
66652505.0@jobsub02.fnal.gov  - PASS
```
  
4.  submit -f dropbox://file1 -f file2 - PASS
```
~sbhat/jobsub_lite/bin/jobsub_submit -G nova -f /pnfs/nova/scratch/users/sbhat/a -f dropbox://testfile2 --onsite file://dash-f-dropbox.sh a testfile2
 66663457.0@jobsub02.fnal.gov  -- found bug
 66663467.0@jobsub02.fnal.gov -- found bug
66670499.0@jobsub02.fnal.gov -- FAILED.  I think there's a bug where we don't support -f dropbox for relative paths properly

Tried this:
~sbhat/jobsub_lite/bin/jobsub_submit -G nova -f /pnfs/nova/scratch/users/sbhat/a -f dropbox:///home/sbhat/FileUploadTests/testfile2 --onsite file://dash-f-dropbox.sh a testfile2
66672335.0@jobsub02.fnal.gov -- another bug
If this works, then we'll know there's a bug with the way the tarball to upload is getting created.

~sbhat/jobsub_lite/bin/jobsub_submit -G nova -f /pnfs/nova/scratch/users/sbhat/a -f dropbox:///home/sbhat/FileUploadTests/testfile2 --onsite file:///home/sbhat/FileUploadTests/dash-f-dropbox.sh a testfile2
66672579.0@jobsub02.fnal.gov - FAIL. Something is wrong in the script.  Debugging
 66675553.0@jobsub02.fnal.gov  -- another bug (typo)
 66676660.0@jobsub02.fnal.gov - PASS (finally - this is why we test)
 ```

5.  submit -f dropbox://file1 -f dropbox://file2
  ```
  ~sbhat/jobsub_lite/bin/jobsub_submit -G fermilab -f dropbox://testfile -f dropbox://testfile2 --onsite file://dash-f-dropbox.sh testfile testfile2
  (RCDS upload)
  66652050.0@jobsub02.fnal.gov 
   66652213.0@jobsub02.fnal.gov 
  
  66663458.0@jobsub02.fnal.gov -- found bug
   66663473.0@jobsub02.fnal.gov  -- unable to remove generated tarfile (why?) -- found bug
  66670506.0@jobsub02.fnal.gov 
  66681745.0@jobsub02.fnal.gov 
  
  "Notice: unable to remove generated tarfile ..tgz"
  ```
  Worked

But this works?
```
Notice: unable to remove generated tarfile FileUploadTests.tgz
~sbhat/jobsub_lite/bin/jobsub_submit -G fermilab -f dropbox:///home/sbhat/FileUploadTests/testfile -f dropbox:///home/sbhat/FileUploadTests/testfile2 --onsite file:///home/sbhat/FileUploadTests/dash-f-dropbox.sh testfile testfile2
66681820.0@jobsub02.fnal.gov 
```
Worked

6.  submit --tar-file-name dropbox://file1- PASS
```
 ~sbhat/jobsub_lite/bin/jobsub_submit -G fermilab --tar-file-name dropbox:///home/sbhat/FileUploadTests/testfiles.tar --onsite file:///home/sbhat/FileUploadTests/tar-file-name.sh 1

66681699.0@jobsub02.fnal.gov - wrong executable
66684328.0@jobsub02.fnal.gov - found bug
66684432.0@jobsub02.fnal.gov - bug in script
66684521.0@jobsub02.fnal.gov - bug in script
66687348.0@jobsub02.fnal.gov - PASS

```

7.  submit --tar-file-name dropbox://file1 -f file2 - PASS
```
~sbhat/jobsub_lite/bin/jobsub_submit -G nova --tar-file-name dropbox:///home/sbhat/FileUploadTests/testfiles.tar -f /pnfs/nova/scratch/users/sbhat/a --onsite file:///home/sbhat/FileUploadTests/tar-dash-f-mix.sh --num-tars 1 --files a
66701916.0@jobsub02.fnal.gov - bug in script
60000615.0@jobsub01.fnal.gov - PASS
```

8.  submit --tar-file-name dropbox://file1 -f dropbox://file2 - PASS

```~sbhat/jobsub_lite/bin/jobsub_submit -G fermilab  --tar-file-name dropbox:///home/sbhat/FileUploadTests/testfiles.tar -f dropbox:///home/sbhat/FileUploadTests/testfile --onsite file:///home/sbhat/FileUploadTests/tar-dash-f-mix.sh --num-tars 1 --files testfile
60000844.0@jobsub01.fnal.gov - PASS
```

9.  submit --tar-file-name dropbox://file1 --tar-file-name dropbox://file2 - PASS
```
~sbhat/jobsub_lite/bin/jobsub_submit -G fermilab --tar-file-name dropbox:///home/sbhat/FileUploadTests/testfiles.tar --tar-file-name dropbox:///home/sbhat/57107386.0@jobsub01.fnal.gov.tgz --onsite file:///home/sbhat/FileUploadTests/tar-file-name.sh 2

66688530.0@jobsub02.fnal.gov - PASS
```


10. submit --tar-file-name tardir://dir1 --tar-file-name dropbox://file2 - PASS
```
~sbhat/jobsub_lite/bin/jobsub_submit -G fermilab  --tar-file-name tardir:///home/sbhat/TestJobs/TestDir --tar-file-name  dropbox:///home/sbhat/FileUploadTests/testfiles.tar --onsite file:///home/sbhat/FileUploadTests/tar-file-name.sh 2
60005307.0@jobsub01.fnal.gov 

```

11. submit --tar-file-name tardir://dir1 --tar-file-name tardir://dir2 - PASS
```
 ~sbhat/jobsub_lite/bin/jobsub_submit -G fermilab  --tar-file-name tardir:///home/sbhat/TestJobs/TestDir --tar-file-name  tardir:///home/sbhat/TestJobs/TestDirTarfile --onsite file:///home/sbhat/FileUploadTests/tar-file-name.sh 2
 60005324.0@jobsub01.fnal.gov - PASS
 ```

**Comment by shreyb** [comment]
--skip-check tests look good!  Found one bug, which I fixed.  After I run unit tests, I'll move the PR to "ready for review".

***
### Now with --skip-check rcds


1.  submit --skip-check rcds -f dropbox://file1 -f file2 - PASS
```
~sbhat/jobsub_lite/bin/jobsub_submit -G nova --skip-check rcds -f /pnfs/nova/scratch/users/sbhat/a -f dropbox:///home/sbhat/FileUploadTests/testfile2 --onsite file:///home/sbhat/FileUploadTests/dash-f-dropbox.sh a testfile2

60040439.0@jobsub01.fnal.gov - FOUND BUG
60041574.0@jobsub01.fnal.gov - PASS
```

2.  submit --skip-check rcds -f dropbox://file1 -f dropbox://file2 - PASS
```
~sbhat/jobsub_lite/bin/jobsub_submit -G fermilab --skip-check rcds -f dropbox:///home/sbhat/FileUploadTests/testfile -f dropbox:///home/sbhat/FileUploadTests/testfile2 --onsite file:///home/sbhat/FileUploadTests/dash-f-dropbox.sh testfile testfile2
60042385.0@jobsub01.fnal.gov 

```

3.  submit --skip-check rcds --tar-file-name dropbox://file1- PASS
```
 ~sbhat/jobsub_lite/bin/jobsub_submit -G fermilab --skip-check rcds --tar-file-name dropbox:///home/sbhat/FileUploadTests/testfiles.tar --onsite file:///home/sbhat/FileUploadTests/tar-file-name.sh 1
60042386.0@jobsub01.fnal.gov 
```

4.  submit --skip-check rcds --tar-file-name dropbox://file1 -f file2 - PASS
```
~sbhat/jobsub_lite/bin/jobsub_submit -G nova --skip-check rcds --tar-file-name dropbox:///home/sbhat/FileUploadTests/testfiles.tar -f /pnfs/nova/scratch/users/sbhat/a --onsite file:///home/sbhat/FileUploadTests/tar-dash-f-mix.sh --num-tars 1 --files a
60044282.0@jobsub01.fnal.gov 

Nice:
Looking for file /cvmfs/fifeuser1.opensciencegrid.org/sw/nova/dbb9726d8e79c49d523ce4684b58b2e6cd7d1e35855ca24b2ab6508b3a3c8251 on RCDS.  Try 1 of 40
Looking for file /cvmfs/fifeuser2.opensciencegrid.org/sw/nova/dbb9726d8e79c49d523ce4684b58b2e6cd7d1e35855ca24b2ab6508b3a3c8251 on RCDS.  Try 2 of 40
Looking for file /cvmfs/fifeuser4.opensciencegrid.org/sw/nova/dbb9726d8e79c49d523ce4684b58b2e6cd7d1e35855ca24b2ab6508b3a3c8251 on RCDS.  Try 3 of 40
Looking for file /cvmfs/fifeuser4.opensciencegrid.org/sw/nova/dbb9726d8e79c49d523ce4684b58b2e6cd7d1e35855ca24b2ab6508b3a3c8251 on RCDS.  Try 4 of 40
Looking for file /cvmfs/fifeuser1.opensciencegrid.org/sw/nova/dbb9726d8e79c49d523ce4684b58b2e6cd7d1e35855ca24b2ab6508b3a3c8251 on RCDS.  Try 5 of 40
Looking for file /cvmfs/fifeuser4.opensciencegrid.org/sw/nova/dbb9726d8e79c49d523ce4684b58b2e6cd7d1e35855ca24b2ab6508b3a3c8251 on RCDS.  Try 6 of 40
Looking for file /cvmfs/fifeuser1.opensciencegrid.org/sw/nova/dbb9726d8e79c49d523ce4684b58b2e6cd7d1e35855ca24b2ab6508b3a3c8251 on RCDS.  Try 7 of 40
Looking for file /cvmfs/fifeuser3.opensciencegrid.org/sw/nova/dbb9726d8e79c49d523ce4684b58b2e6cd7d1e35855ca24b2ab6508b3a3c8251 on RCDS.  Try 8 of 40
```

5.  submit --skip-check rcds --tar-file-name dropbox://file1 -f dropbox://file2 - PASS
```
~sbhat/jobsub_lite/bin/jobsub_submit -G fermilab  --skip-check rcds --tar-file-name dropbox:///home/sbhat/FileUploadTests/testfiles.tar -f dropbox:///home/sbhat/FileUploadTests/testfile --onsite file:///home/sbhat/FileUploadTests/tar-dash-f-mix.sh --num-tars 1 --files testfile
60044461.0@jobsub01.fnal.gov
```
6.  submit --skip-check rcds --tar-file-name dropbox://file1 --tar-file-name dropbox://file2 - PASS
```
~sbhat/jobsub_lite/bin/jobsub_submit -G fermilab --skip-check rcds --tar-file-name dropbox:///home/sbhat/FileUploadTests/testfiles.tar --tar-file-name dropbox:///home/sbhat/57107386.0@jobsub01.fnal.gov.tgz --onsite file:///home/sbhat/FileUploadTests/tar-file-name.sh 2
60047779.0@jobsub01.fnal.gov 
```

7. submit --skip-check rcds --tar-file-name tardir://dir1 --tar-file-name dropbox://file2  - PASS
```
~sbhat/jobsub_lite/bin/jobsub_submit -G fermilab  --skip-check rcds --tar-file-name tardir:///home/sbhat/TestJobs/TestDir --tar-file-name  dropbox:///home/sbhat/FileUploadTests/testfiles.tar --onsite file:///home/sbhat/FileUploadTests/tar-file-name.sh 2
60047883.0@jobsub01.fnal.gov 
```

8. submit --skip-check rcds --tar-file-name tardir://dir1 --tar-file-name tardir://dir2 - PASS
```
 ~sbhat/jobsub_lite/bin/jobsub_submit -G fermilab  --skip-check rcds --tar-file-name tardir:///home/sbhat/TestJobs/TestDir --tar-file-name  tardir:///home/sbhat/TestJobs/TestDirTarfile --onsite file:///home/sbhat/FileUploadTests/tar-file-name.sh 2
60051306.0@jobsub01.fnal.gov 
```

9.  One test with completely new rcds upload (dropbox:)
``` 
~sbhat/jobsub_lite/bin/jobsub_submit -G fermilab  --skip-check rcds --tar-file-name dropbox:///home/sbhat/TestJobs/test_file.txt --onsite file:///home/sbhat/FileUploadTests/tar-file-name.sh 1
60051331.0@jobsub01.fnal.gov - PASS, but I just want to be sure I'm really uploading a new tarball:
66712045.0@jobsub02.fnal.gov 
```

**Comment by shreyb** [comment]
All unit/integration tests pass.  Marking #324 as ready for review.
