### ISSUE TITLE
Need MANPATH check in /etc/profile.d/jobsub_list.csh 

### ISSUE THREAD

**Issue by brianyanny** [marcmengel/jobsub_lite#349]
For csh/tcsh users, the /etc/profile.d/jobsub_list.csh file has these lines:

if ( $euid != 0 ) then
    set path = ( /opt/jobsub_lite/bin $path )
    setenv MANPATH /opt/jobsub_lite/man:$MANPATH
endif

This causes an error if MANPATH is not predefined (which it is not).
Need to change to:
if ( $euid != 0 ) then
    set path = ( /opt/jobsub_lite/bin $path )
    setenv MANPATH /opt/jobsub_lite/man
endif

Or some check on the MANPATH variable to see if it exists before referencing.

**Comment by shreyb** [comment]
Opened https://github.com/marcmengel/jobsub_lite_config/issues/9, since the change needs to be made in that repository.
