### ISSUE TITLE
Make sure all jobsub querying commands (q, rm, hold, release) respect dotted cluster and undotted cluster format

### ISSUE THREAD

**Issue by rlcee** [marcmengel/jobsub_lite#370]
This message output seems confused:
> jobsub_rm --jobid=60475214.@jobsub01.fnal.gov --role=Production

Couldn't find/remove all jobs of user "60475214."

> jobsub_rm --version
jobsub_lite version 1.2

Lisa noted:
condor_q ... 60475214.@jobsub01.fnal.gov ... works but
condor_rm ... 60475214.@jobsub01.fnal.gov ... does not.

Please accept and process this command correctly, or reject it with 
a targeted error message such as "jobid unknown format".

**Comment by shreyb** [comment]
@rlcee - I hope you don't mind: I'm going to change the title of this issue to make it a little more specific.

**Comment by marcmengel** [comment]
So... basically if we stripped trailing dots off of the jobid, we would get consistent results?  Lets see...

**Comment by marcmengel** [comment]
So the change in jobsub_cmd seems to get most of it, now for jobsub_fetchlog...
