### ISSUE TITLE
Condor wrappers should use condor CLI style schedd specification

### ISSUE THREAD

**Issue by shreyb** [marcmengel/jobsub_lite#40]
Currently, our condor wrappers that query the schedd (`condor_q`, `condor_rm`, etc.) use the jobsub-style convention for specifying a schedd:  `cluster.job@schedd`.  To allow our condor wrappers to look as similar to condor as possible, we should use the same convention as HTCondor (`-name <schedd> jobid`).

**Comment by marcmengel** [comment]
The `-name schedd` works too, as the wrappers currently are; but we do accept the `cluster.job@schedd syntax`, and convert it to` -name schedd  ... cluster.job`.  

So I'm thinking we may not need this issue?   Or should we only accept the @schedd syntax if you invoked the wrapper as "jobsub_" something?

**Comment by shreyb** [comment]
This has been fixed for some time now.  Closing issue.
