### ISSUE TITLE
Implement DESIRED_USAGE_MODEL flags

### ISSUE THREAD

**Issue by shreyb** [marcmengel/jobsub_lite#49]
Currently, jobs don't run in jobsub_lite unless a flag like `--resources_provides=DESIRED_USAGE_MODEL=DEDICATED` (I'm going from memory here - the assignee should check for the actual correct flag) is provided.  We need to implement two flags:

`--onsite`, which will add DEDICATED,OPPORTUNISTIC
`--offsite`, which will add OFFSITE

And have no flag default to `DESIRED_USAGE_MODEL=DEDICATED,OPPORTUNISTIC,OFFSITE`.

The actual flag names and implementation here are a suggestion - the assignee is of course free to come up with a better scheme.

**Comment by shreyb** [comment]
Whoever does this should also do #5 at the same time.

**Comment by goodenou** [comment]
Fixed in PR #101
