### ISSUE TITLE
Implement role support for get_creds()

### ISSUE THREAD

**Issue by shreyb** [marcmengel/jobsub_lite#51]
https://github.com/marcmengel/jobsub_lite/blob/8d22209b58a004bd17acc6c44e47686a765a5b60/lib/creds.py#L20

Right now, `get_creds()` will always call `fake_ifdh` with no arguments, which will allow the role-selection in `fake_ifdh` to rely on the environment.  We want to make this more intelligent, and allow for us to pass a role in.  Either check for it in `args`, or specifically allow for a `role` argument that gets passed into fake_ifdh, depending on if it's the default "Analysis" role or not.

**Comment by marcmengel** [comment]
So this is half fixed overall; we call fake_ifdh methods directly now with role bits, but bin/jobsub_submit, lib/dagnabbit.py, and lib/tarfiles.py don't pass in args when they could(?) to get_creds().
