### ISSUE TITLE
Managed Tokens-Related Changes

### ISSUE THREAD

**Issue by shreyb** [marcmengel/jobsub_lite#65]
This issue/document follows a large discussion with @DrDaveD, who maintains [htgettoken](https://github.com/fermitools/htgettoken) and [condor_vault_storer](https://github.com/htcondor/htcondor/blob/master/src/condor_credd/condor_credmon_oauth/condor_vault_storer), both of which we use to get credentials.

### Managed Tokens Idea

We want to have a script/service running on a crontab that generates vault tokens for production users (e.g. dunepro, mu2epro, etc.).  It will then transfer these tokens to the experiments' submit nodes, from which they can run `jobsub_submit` and other grid tools.

### Issue with extra authentication

While testing small-scale versions of this service for DUNE, Ken Herner and I have found that we, acting as simulated end-users, often have to reauthenticate via CILogon website and our SERVICES credentials to obtain a bearer token.  The way that `htgettoken` works, since we already would have a valid vault token, we should not have to authenticate to get a bearer token from the vault.  

### Root cause

Currently, our Managed Tokens script uses a special Kerberos group principal and invokes `condor_vault_storer`, which generates two copies of the vault token: 

1. `/tmp/vt_u$(id -u)`
2. `/tmp/vt_u$(id -u)-SERVICE` where `SERVICE` is simply a concatenation of `issuer_role`.  So the full path would be something like `/tmp/vt_u12345-dune` or `tmp/vt_u12345-dune_production`

Crucially, `condor_vault_storer` looks in the _second_ location to figure out whether or not it needs to re-generate a vault token and store it in the `condor_credmon`.  This will become important shortly.

One of the first actions `jobsub_submit` does is to run htgettoken (via `get_creds()`):

https://github.com/marcmengel/jobsub_lite/blob/250859b2c8066d375d398bf0850bbbcbc22a86c9/bin/jobsub_submit#L174

By default, `htgettoken` _will only create the first copy of the vault token above_.  Thus, when we go to submit the job, `condor_submit`, invoked by `jobsub_submit`, runs`condor_vault_storer`, which will not see a vault token in the second location and will try to regenerate another vault token, even though one exists in the first location.

#### Further complication

In the troubleshooting of this issue, Ken and I would often regenerate the vault token manually by rerunning the Managed Proxy protoype script.  This script currently clears the kerberos cache of our user kerberos ticket, and puts the special group kerberos ticket into the cache.  If we then try to run `jobsub_submit`, this causes the obtaining of an X509 proxy to fail.

### Solution, and the work item for this issue

We think we can solve both issues by simply having jobsub_lite run `condor_vault_storer` with the appropriate argument instead of `htgettoken` on  https://github.com/marcmengel/jobsub_lite/blob/master/lib/fake_ifdh.py#L76.  This would result in `condor_vault_storer` being invoked twice on each `condor_submit` (first manually, second automatically by `condor_submit`), which is OK (we currently similarly invoke `htgettoken` twice).

The Managed Tokens service would run as is, generating both vault tokens, and transferring them both to the end user's submit machine.  When the user then runs `jobsub_submit`:

1. For an Analysis user, `condor_vault_storer` will get the correct vault and bearer tokens, and when `condor_submit` is invoked, this second invocation of `condor_vault_storer` will see the correct vault token and proceed.
2. For a production user, the first invocation of `condor_vault_storer` will see that the vault tokens are already in place (due to the Managed Tokens service), and simply get the bearer token.  The second invocation of `condor_vault_storer` will simply do the same as in the Analysis case.

### Additional Notes
1. The kerberos ticket the end user has (their own) when logging into the production account should not matter for the purpose of getting a token.  The way I describe the use case here, the vault token along with the correct credkey passed to `$HTGETTOKENOPTS` should be sufficient for authentication to get the proper bearer token.
2. The Managed Tokens service should possibly NOT create the bearer token when it runs `condor_vault_storer`.  This can also be done by passing --nobearertoken in `$HTGETTOKENOPTS`.
3.  I tested the end-effect of doing this using fifeutilgpvm01 and my dev node, fermicloud525.  On fifeutilgpvm01, I ran the Managed Tokens prototype script, and transferred the files to fermicloud525 with the same paths.  I then logged into fermicloud525 as dunepro, and after setting up the environment variables (`$HTGETTOKENOPTS` and `$_condor_COLLECTOR_HOST`, was able to submit jobs using those vault tokens.
4. We should explore reverting to the Managed Tokens service running as a service account (rexbatch) and operating from there, rather than needing to `su` as the various users.
5. For the case of managed tokens only (We'd have to figure out how to discern that), @DrDaveD also suggested having `--noidc` added to the HTGETTOKENOPTS for `jobsub_submit`.

**Comment by shreyb** [comment]
Managed tokens prototype is complete.  See https://github.com/shreyb/managed-tokens

**Comment by shreyb** [comment]
Note that this is no longer a requirement for managed tokens, since the workaround of having managed tokens simply deposit two copies of the vault token works fine.  We can push this off after some discussion with Dave D about how necessary this actually is.

**Comment by shreyb** [comment]
@DrDaveD - is there any reason we should keep thinking about moving jobsub_lite to using `condor_vault_storer` as opposed to what we currently do (`htgettoken`)?  Currently, we set `BEARER_TOKEN_FILE` and call `htgettoken`, and the subsequent `condor_submit` calls `condor_vault_storer` if necessary.  This works for our current setup, since `BEARER_TOKEN_FILE` is respected by both utilities.

The other good thing about using `htgettoken` in our standard token code is that we don't actually have to store the vault token unless we're doing a submit (i.e. `jobsub_q`, `jobsub_fetchlog`, etc. don't have to actually store a token in the condor credd).

**Comment by shreyb** [comment]
Closing this.  We can reopen if it comes out that we need to change `htgettoken` calls to `condor_vault_storer`

**Comment by DrDaveD** [comment]
It still might make a difference for people who do not have kerberos, I think.  For them I think they will need to do OIDC authentication twice at the beginning of each week, once for the original htgettoken and again for the condor_vault_storer that condor_submit calls.
