### ISSUE TITLE
New bug in master wrt template rendering

### ISSUE THREAD

**Issue by shreyb** [marcmengel/jobsub_lite#66]
https://github.com/marcmengel/jobsub_lite/blob/250859b2c8066d375d398bf0850bbbcbc22a86c9/templates/simple/simple.sh#L323

This line is an example of a bug introduced in f6fbb3d8292f4c5e3a51c1a352920bf2692e4e2f, which occurs when any template variable that is set to "None" by default (like `timeout`) is checked like this.  The intended behavior is that if the variable is undefined or `None`, that we omit the portion of the script that invokes it.  Instead, since the variable _is_ defined, as `None`, the template tries to substitute `None` for the value of the variable, which usually causes problems.  Look through the various templates and fix this.

This breaks even the simplest of jobs.

**Comment by marcmengel** [comment]
I thought I got all those in pull #64... no I take it back.  I did all the .cmd files, but not the scripts...

**Comment by marcmengel** [comment]
Looks like I missed 2:
```
[mengel@fifeutilgpvm01 jobsub_lite]$ git grep 'is defined\s*%}' 
templates/dag/dag.dag.condor.sub:{% if subgroup is defined %}
templates/simple/simple.sh:{%if timeout is defined %} timeout {{timeout}} {%endif%} $JOBSUB_EXE_SCRIPT {{exe_arguments|join(" ")
[mengel@fifeutilgpvm01 jobsub_lite]$ 
```

**Comment by marcmengel** [comment]
Oh, and this could drop a None in:
templates/dag/dag.dag.condor.sub:`{% if role is defined and role != 'Analysis' %}`

**Comment by marcmengel** [comment]
Okay, now I've covered all the items found by `git grep is.defined` which I think gets them all.  #66

**Comment by marcmengel** [comment]
Merging #66 closes this.
