### ISSUE TITLE
Implement clearing out of troublesome environment variables

### ISSUE THREAD

**Issue by shreyb** [marcmengel/jobsub_lite#84]
There are a number of known environment variables that cause issues when running grid jobs in singularity containers.  We should, by default, clear those, and provide a flag to keep those variables in place.

This list of variables should be _well-documented_.

**Comment by marcmengel** [comment]
Pull request: #87

Added writeup on wrapper script to local wiki: https://github.com/marcmengel/jobsub_lite/wiki/Jobsub-wrapper-script
we should get this moved to the fife_wiki. https://fifewiki.fnal.gov/wiki/
