### ISSUE TITLE
jobsub_q @jobsubdevgpvm01.fnal.gov does not give detailed queue information 

### ISSUE THREAD

**Issue by goodenou** [marcmengel/jobsub_lite#92]
Output from jobsub_q @jobsubdevgpvm01.fnal.gov is not complete. The specifics are missing.

Here is an example of the output that one gets:
-- Schedd: jobsubdevgpvm01.fnal.gov : <131.225.240.23:9615?... @ 08/24/22 14:52:10
OWNER BATCH_NAME      SUBMITTED   DONE   RUN    IDLE   HOLD  TOTAL JOB_IDS

Total for query: 0 jobs; 0 completed, 0 removed, 0 idle, 0 running, 0 held, 0 suspended 
Total for all users: 28 jobs; 9 completed, 0 removed, 17 idle, 0 running, 2 held, 0 suspended

Here is an example of the output that one SHOULD get:
-- Schedd: jobsubdevgpvm01.fnal.gov : <131.225.240.23:9615?... @ 08/24/22 14:51:34
OWNER    BATCH_NAME    SUBMITTED   DONE   RUN    IDLE   HOLD  TOTAL JOB_IDS
goodenou ID: 736      8/23 13:54      _      _      _      _      1 736.0
goodenou ID: 737      8/23 15:16      _      _      _      _      1 737.0
goodenou ID: 739      8/24 14:51      _      _      1      _      1 739.0

Total for query: 3 jobs; 2 completed, 0 removed, 1 idle, 0 running, 0 held, 0 suspended 
Total for goodenou: 3 jobs; 2 completed, 0 removed, 1 idle, 0 running, 0 held, 0 suspended 
Total for all users: 28 jobs; 8 completed, 0 removed, 18 idle, 0 running, 2 held, 0 suspended

**Comment by marcmengel** [comment]
So I think this is because we're putting an empty string into the argument list when we strip out the @jobsubdevgvpm01.fnal.gov.  So instead of:
`condor_q -G fermilab -name jobsubdevgpvm01.fnal.gov`
which works, we end up with
`condor_q -G fermilab -name jobsubdevgpvm01 ''`
which doesn't...

**Comment by marcmengel** [comment]
So I think over here;
https://github.com/marcmengel/jobsub_lite/blob/master/bin/jobsub_cmd#L72
we need to check for "i" being empty before we append it to the argument list...

**Comment by marcmengel** [comment]
Fixed in #96
