### ISSUE TITLE
DAG issues 

### ISSUE THREAD

**Issue by marcmengel** [marcmengel/jobsub_lite#94]
A few issues noted by vito:

I got small-ish issue in the DAG setup, the dagbegin.cmd and dagend.cmd are inheriting resource requests from the jobsub_submit command, which could mean few memory GB and 10s GB of disk for jobs just starting/ending the SAM project, I think in current jobsub_client those jobs have their own pre-sets for resource requirements
[3:09](https://fnal.slack.com/archives/C0404M5100Z/p1661458148411139)
also, all user jobs in the DAG are named WORKER_0 , in current jobsub_client, the index suffix is increasing
New
[3:09](https://fnal.slack.com/archives/C0404M5100Z/p1661458192637049)
 ID      OWNER/NODENAME      SUBMITTED     RUN_TIME ST PRI SIZE CMD
 761.0   vito               8/24 20:20   0+02:41:04 R  0    0.0 dagman_wrapper.sh -p 0 -f -l . ...
 763.0    |-WORKER_0        8/24 20:22   0+00:00:00 I  0    0.0 simple.sh --debug --find_setups ...
 763.1    |-WORKER_0        8/24 20:22   0+00:00:00 I  0    0.0 simple.sh --debug --find_setups ...
 763.2    |-WORKER_0        8/24 20:22   0+00:00:00 I  0    0.0 simple.sh --debug --find_setups ...

**Comment by marcmengel** [comment]
Now we get different worker_n nodenames, and the jobsub submit memory requirements etc don't get applied to the dagbegin/dagend jobs.  I also got some semblance of JOBSUBJOBSEGMENT working, where each jobsub job in the dag gets a sequential number.

**Comment by shreyb** [comment]
Can this be closed?  Or does the reversion commit (3fbc3e8) mean we have to keep it open?

**Comment by marcmengel** [comment]
It means I had another change on the branch I wanted to push that didn't get in the merge, and I hit the wrong button on github.  Now I need to figure out what happenned...

**Comment by marcmengel** [comment]
So it looks like my goofed-up revert didn't go onto master, and is just a stub.  Put a comment on it, and I think we can close this out. Sorry for the confusion.
